# Generated by Django 4.1.7 on 2023-08-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_contact_newslatter_alter_checkout_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pic', models.ImageField(upload_to='uploads/testimonials')),
            ],
        ),
    ]
