# Generated by Django 4.1.7 on 2023-08-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
